### ISSUE TITLE
Follow up on issue #59

### ISSUE THREAD

**Issue by edidah** [JensUweUlrich/ReadBouncer#60]
Hi Jens-Uwe, I hade raised an issue on MinKnow not connecting correctly: I have attached link below,
https://github.com/JensUweUlrich/ReadBouncer/issues/59#issue-1418263480
We haven't resolve yet any further assistance we be of much help.

Thank you

**Comment by JensUweUlrich** [comment]
Sorry, I thought you resolved the issue by using port 9504. 
So usually you should be able to connect to MinKNOW using port 9502, which is the port to connect to the MK connection manager. Can you please tell me which version of MinKNOW you have installed on your machine?
When you start MinKNOW, do you see the simulated device `MS0000`?

**Comment by edidah** [comment]
Sorry for the late response.  The Minknow version is MiKnow v.22.05.7. We haven't edited settings to get the simulated device MS0000 for fear of interrupting other sequencing activities. Can the run be done minus the simulated device?

**Comment by JensUweUlrich** [comment]
Then that's the issue here. For your understanding: ReadBouncer connects to port 9502, which is the MinKNOW manager port. ReadBouncer than asks for the port of the given device name. So in our use case with a simulated device, it asks for the port of device `MS00000`. Since you did not set up the simulated device, MinKNOW manager does not return a valid port and thus we cannot connect to the device.

**Comment by edidah** [comment]
Hi Jens,
I am still stuck on the simulated device. We have installed the ReadBouncer on GridION device which runs MinKnow. Is the simulated device a virtual machine beside the GridION? And do you have guidelines to setup the simulated device?

**Comment by JensUweUlrich** [comment]
Hi 

you can create a simulated device by providing the minknow manager with the dedicated parameter. Therefore you first need to modify the following file `/lib/systemd/system/minknow.service` and edit the following lines
```
[Service]
ExecStart=/opt/ont/minknow/bin/mk_manager_svc --simulated-integrated-devices 1
```
Then you need to reload the daemon via `sudo systemctl daemon-reload` and restart the MinKNOW service via `sudo service minknow restart` (In some cases you need to reboot your operating system). Your MinKNOW instance will now show a simulated device named MS00000 that will playback the bulkfile rather than live sequencing.

We also explained how to setup the testing with a simulated device [here](https://github.com/JensUweUlrich/ReadBouncer#astest)

**Comment by edidah** [comment]
Thank you Jens, I will try this. I was wondering what happens when I want to do a real adaptive sampling experiment using the software. Do I still need the simulated device or how do I go about setting it up?

**Comment by JensUweUlrich** [comment]
@edidah 

No, you don't need the simulated device for a real adaptive sampling run. In a real experiment, you enter the flowcell into the sequencing device, and MinKNOW will display the name of the flowcell immediately. Instead of `MS00000` you only need to tell ReadBouncer the name/ID of the flowcell.

**Comment by edidah** [comment]
We have been struggling to set up an adaptive sampling run that uses the ReadBouncer for a while now. Despite us feeding the Flow cell ID to the MinKnow the ReadBouncer still doesn't prompt us to start sequencing; see the attached image. Should one start the run from the MinKnow? If yes how should I setup the run parameters and at what step will I integrate the ReadBouncer? Kindly outline for us the steps needed to start adaptive sampling using the ReadBouncer especially from starting the ReadBouncer, setting the run parameters, starting the run on the MinKnow.

Thanks,
Edidah

**Comment by JensUweUlrich** [comment]
Just to make sure: Are you using the latest ReadBouncer version or version 1.1? ReadBouncer 1.1 is not compatible with MinKNOW version 5.

**Comment by JensUweUlrich** [comment]
Are you able to start a run on the simulated device? Can you also confirm that the device `MS00000` is displayed in your MinKNOW GUI? I forgot, that you are running a GridION and maybe the device/flowcell name is different than with the MinION.
Another possibility is that MinKNOW blocks the grpc connection. Can you please open `/opt/ont/minknow/conf/app_conf` file and post the values for 
```
"local_connection_only": "all_open",
"guest_access_default": "local_only"
```

**Comment by edidah** [comment]
Hi Jens, we ran the GridION with the suggested values. However, from the output we are not still able to establish a successful connection to the MinKnow: kindly find the attached screenshots for further assistance.

<img width="427" alt="MicrosoftTeams-image" src="https://user-images.githubusercontent.com/44297932/201929692-73e33210-cab4-4742-a26e-d86ce2f3b557.png">


<img width="1041" alt="Screenshot 2022-11-15 at 16 17 29" src="https://user-images.githubusercontent.com/44297932/201929210-1c2d3efd-d2c3-492b-977a-2035e3d147f2.png">

**Comment by JensUweUlrich** [comment]
ok, so it's not the grpc server that refuses the connection. Could it be that the simulated device is named something like `XS1` instead of `MS00000`. Maybe you could provide me with screenshots of your MinKNOW GUI when you try to start a run on the suimulated device.
